config/routes.rb
Rails.application.routes.draw do
  resources :farm_notes

  #include this route in any app using NewsStories
  # mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :news_stories

  resources :businesses
end

app/models/farm_note.rb
class FarmNote < ActiveRecord::Base
end

app/controllers/farm_notes_controller.rb
class FarmNotesController < ApplicationController
  before_action :set_farm_note, only: [:show, :edit, :update, :destroy]

  # GET /farm_notes
  def index
    @farm_notes = FarmNote.all
  end

  # GET /farm_notes/1
  def show
  end

  # GET /farm_notes/new
  def new
    @farm_note = FarmNote.new
  end

  # GET /farm_notes/1/edit
  def edit
  end

  # POST /farm_notes
  def create
    @farm_note = FarmNote.new(farm_note_params)

    if @farm_note.save
      redirect_to @farm_note, notice: 'Farm note was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /farm_notes/1
  def update
    if @farm_note.update(farm_note_params)
      redirect_to @farm_note, notice: 'Farm note was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /farm_notes/1
  def destroy
    @farm_note.destroy
    redirect_to farm_notes_url, notice: 'Farm note was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm_note
      @farm_note = FarmNote.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def farm_note_params
      params.require(:farm_note).permit(:has_farm_notes_id, :has_farm_notes_type, :content)
    end
end

app/views/farm_notes/_form.html.erb
<%= form_for(@farm_note) do |f| %>
  <% if @farm_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@farm_note.errors.count, "error") %> prohibited this farm_note from being saved:</h2>

      <ul>
      <% @farm_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :has_farm_notes_id %><br>
    <%= f.number_field :has_farm_notes_id %>
  </div>
  <div class="field">
    <%= f.label :has_farm_notes_type %><br>
    <%= f.text_field :has_farm_notes_type %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/farm_notes/edit.html.erb
<h1>Editing Farm Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @farm_note %> |
<%= link_to 'Back', farm_notes_path %>

app/views/farm_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Farm Notes</h1>

<table>
  <thead>
    <tr>
      <th>Has farm notes</th>
      <th>Has farm notes type</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @farm_notes.each do |farm_note| %>
      <tr>
        <td><%= farm_note.has_farm_notes_id %></td>
        <td><%= farm_note.has_farm_notes_type %></td>
        <td><%= farm_note.content %></td>
        <td><%= link_to 'Show', farm_note %></td>
        <td><%= link_to 'Edit', edit_farm_note_path(farm_note) %></td>
        <td><%= link_to 'Destroy', farm_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Farm note', new_farm_note_path %>

app/views/farm_notes/new.html.erb
<h1>New Farm Note</h1>

<%= render 'form' %>

<%= link_to 'Back', farm_notes_path %>

app/views/farm_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Has farm notes:</strong>
  <%= @farm_note.has_farm_notes_id %>
</p>

<p>
  <strong>Has farm notes type:</strong>
  <%= @farm_note.has_farm_notes_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @farm_note.content %>
</p>

<%= link_to 'Edit', edit_farm_note_path(@farm_note) %> |
<%= link_to 'Back', farm_notes_path %>